### ISSUE TITLE
Moon "phase" and "phase name"

### ISSUE THREAD

**Issue by trevorturk** [rhannequin/astronoby#101]
### Problem this feature will solve

With the moon's current attributes, we get `illuminated_fraction` but not the name of the current `moon_phase`. I believe we discussed this a while back, and we realized that it's a bit of a tricky problem because essentially a "phase" is more of a "phase event" that occurs at a specific time, as opposed to being something that lasts for an entire day / calendar date. 

However, I believe it's common for people to discuss the moon's illumination in terms of a day / calendar date (i.e. there's a full moon tomorrow) and having a shortcut to obtain this human-readable moon phase name would be useful. 

### Desired solution

We might consider converting `illuminated_fraction` to `phase_name` or such according to a formula. (I'll discuss this a bit more below...) We could also consider first checking against `monthly_phase_events`, which, if rounded to the day, could take precedence over the formula. 

A few years ago, I discussed this with the creators of the Dark Sky API, and this is a summary of the conversation and the resulting code that I've been using in my application for some time. Note that their JSON names are a bit confusing -- in their case `moon_phase` is equivalent to `illuminated_fraction` in Astronoby. Still, I think this could serve as the basis for a formula:

> I have a question about the moon phase data point. I have Ruby code that looks like so:
> 
> if moon_phase == 0.5
>   "full"
> elsif moon_phase.between?(0.5, 0.75)
>   "waning-gibbous-3"
> etc...
> 
> My concern is that the exact comparison of 0.5 might not be ideal if the 0.5 value doesn't last for a full day. The other conditions use ranges and would "win" more often than I'd like. (I'm thinking I'd like a "full moon" day to last for the entire day.) Can you tell me if I should be using a range for the "new" and "full" moons (0.0 and 0.5 respectively) or do those values last for a full day?

> Good question! The answer depends on your use case, of course, but if you want to display the full moon only on the day it occurs, you should use a range of +/- half a day. A lunar month is 29.530587981 days long, which means you want a range of 0.5-0.5/29.530587981 to 0.5+0.5/29.530587981, or 0.4831 to 0.5169. You can do similarly for a new moon, which would then be less than 0.0169 or greater than 0.9831.

Taking this advice, I created a Ruby converter method that looks like this:

```ruby
    if moon_phase.between?(0.0169, 0.2415)
      "Waxing crescent"
    elsif moon_phase.between?(0.2415, 0.2584)
      "First quarter"
    elsif moon_phase.between?(0.2584, 0.4830)
      "Waxing gibbous"
    elsif moon_phase.between?(0.4830, 0.5169)
      "Full"
    elsif moon_phase.between?(0.5169, 0.7246)
      "Waning gibbous"
    elsif moon_phase.between?(0.7246, 0.7753)
      "Last quarter"
    elsif moon_phase.between?(0.7753, 0.9831)
      "Waning crescent"
    else
      "New"
    end
```

This has been working reasonably well for my application (an iOS weather app) and I think it seems reasonably generic and useful for potential inclusion into this gem, so I figured I'd chime in here. I'm working up a wrapper to integrate Astronoby into my application, so I'll report back if I get something working to my liking. 

Thanks for your consideration!

[Update] I think I spoke too soon, and `illuminated_fraction` is not what I'm looking for. 

For example in other Rubygems:

```ruby
SunCalc.moon_illumination(Time.zone.now)
=> {:fraction=>0.9617255644495569, :phase=>0.5626779295167722, :angle=>1.1389579376885706}

Astro::Moon.phase(Time.zone.now.to_datetime).phase
=> 0.5660597883082039
```

...I think you referred to this as the `elongation` but it's a bit complicated how to calculate the "phase" to match these other libraries! 

FWIW here's the Dark Sky documentation about their "moonPhase" attribute:

> moonPhase: The fractional part of the lunation number during the given day: a value of 0 corresponds to a new moon, 0.25 to a first quarter moon, 0.5 to a full moon, and 0.75 to a last quarter moon. (The ranges in between these represent waxing crescent, waxing gibbous, waning gibbous, and waning crescent moons, respectively.)

The "lunation number" links to https://en.wikipedia.org/wiki/New_moon#Lunation_number

[Update 2] I came across this Swift library which seems to handle things how I was thinking of them -- might be worth having a closer look! https://github.com/mannylopez/TinyMoon?tab=readme-ov-file#moon-vs-exactmoon

**Comment by trevorturk** [comment]
Thank you for the very thoughtful comments and information! I'm a bit unsure about what to think, because I agree this isn't exactly scientific (translating the math into human names) and I've done some research and not found a clear agreement from different sources about how to calculate these things. 

I would say that most weather data APIs that provide sun/moon data do provide a "phase name" but as I look around, I'm seeing things split between those (apps and APIs) in terms of how they process "special" phases. The 3 variants I see are:

* Give all phases equal treatment, so a "Full" moon may last for multiple days
* Give "Full" and "New" phases special treatment, so "Full" and "New" moons last a single day
* Give "Full", "New", "First Quarter" and "Last Quarter" phases special treatment, so they all last a single day

All sources I've found allow Waxing/Waning Crescent/Gibbous to last multiple days, but otherwise there is a variation in treatment, and I'm not sure if there is a "correct" answer. So, I suppose if Astronoby were to include a helper, we might want to consider including 3, or an option to decide how to handle those differences, which begs the question if it should be included at all. 

Selfishly, I would like to see Astronoby handle this, because I would like to remove it from the scope of problems I'm making decisions about myself, but I totally understand that it's a complicated thing. 

I'm curious what you think, now!?

**Comment by trevorturk** [comment]
Apologies for the additional comment, but I forgot to mention that I'm a bit confused about the "phase" as-a-number here as it compares to the (I believe very popular) SunCalc library that's been ported to a few languages and the old Dark Sky API. Is that something we can calculate with Astronoby, or is that missing (for now?) -- I see it fairly commonly in data sources, but I think I'm misunderstanding / misinterpreting things here. Since your example `current_phase_name` uses `mean_elongation.degrees` I'm asking since my internal methods (as recommended by Dark Sky) to derive a "phase name" are based on the "phase" as a number between 0-1.

**Comment by trevorturk** [comment]
> I could prevent this and introduce something...

I think I would, but (again) I'm really not 100% sure about any of this. FWIW, looking at other libraries and APIs, I see

* AstroMoon.phase
* IMCCE.api/v1/positions/399&observer=301.phase / 100
* MoonApi.com.advanced.moon.phase
* SunCalc.moon_illumination.phase
* USNO.api/rstt/oneday.fracillum (fraction illuminated?)

Of course, I'm coming at this from a weather app sort of perspective, so note Dark Sky says:

> moonPhase: The fractional part of the lunation number during the given day: a value of 0 corresponds to a new moon, 0.25 to a first quarter moon, 0.5 to a full moon, and 0.75 to a last quarter moon. (The ranges in between these represent waxing crescent, waxing gibbous, waning gibbous, and waning crescent moons, respectively.)

Which means, I think (?) it might be best to name this "phase" or something more specific, but I think it's worth providing, even if you don't change anything else (like leaving `phase_angle` in place). 

> if some phases must last for 1 day, when does this day start and end?

Interestingly, I'm just hooking up another separate set of data for my app which wants to show when the next few "special" phases are coming up. To accomplish this, I'm using Astronoby's `monthly_phase_events` for this month, and the previous/next month. I'm taking the UTC times and converting them into the local time for the user, then converting that into a plain date, instead of a time. 

So, I think, in a way, Astronoby is almost making some decisions for us already, since we can ask it when a special moon phase begins (or when the instant of it occurs) and convert that into a local date... in my base, I'm basically thinking of any timestamp I get from Astronoby as a thing to convert into the user's local timezone, and then moving on from there. 

I'm confusing myself a bit with all of this, so apologies if I'm not explaining myself very well, but I'm trying my best!

**Comment by rhannequin** [comment]
After a long time, I finally took the time to give this another thought.

First I wanted to give a few remarks from your last comment:

> I'm confusing myself a bit with all of this, so apologies if I'm not explaining myself very well, but I'm trying my best!

This is VERY MUCH appreciated. Thank you for taking the time to explain your thoughts with examples, it helps me see the story from another angle.

> IMCCE.api/v1/positions/399&observer=301.phase / 100

I believe `phase` refers here to the _astronomical phase_ mentioned in my previous comment, while what you are looking for is `illuminatedFraction`. If you check the [results for January 2024](https://opale.imcce.fr/api/v1/positions/301?date=2024-01-01T00:00:00&observer=399&step=1D&nbd=31&quantities=il,phase), and if you compare with the visuals from [this form](https://ssp.imcce.fr/forms/phases). For example on January 5th, as seen from the Earth, the Moon has 41.9% of its surface illuminated, but the phase is `99.3`. On January 22nd, it's 86.5% illuminated but the base is `43.1`.
This goes with my previous comment where I believe "phase" is used in the common language to describe the illuminated fraction of the body, but in purely scientific/astronomic context "phase" means another concept.

> I'm taking the UTC times and converting them into the local time for the user, then converting that into a plain date, instead of a time.

That seems good to me, however I suggest you use the new `utc_offset` parameter from `Astronoby::Observer` that will be part of v0.6 to avoid the problem you noticed of Astronoby computing some events for the wrong day. You can then use `Time#getlocal` with the same `utc_offset` to have the local time.

---

Unless I misunderstood your last comment, it looks to me like I could implement `#current_phase_fraction` as defined in my previous comment. It has "phase" in the name so that it helps users select this value for everything "phase-related". It has "fraction" because this would still be a number between 0 and 1. It would be more accessible than `#mean_elongation`, while it would be the same information. It has "current" because it would be an instant value, constantly changing, representing the Moon' state at the requested instant.

I'm aware it doesn't solve the main point of this issue, which is to have a human name for the current phase. But I'm a bit reluctant to introduce it at the moment because there's no universal definition of these names (as we mentioned together, some phases would last several days while major ones don't make sense on multiple days in the common language).
By introducing `#current_phase_fraction`, at least it fixes the problem with `#illuminated_fraction` which doesn't help compute the phase name to our liking (because 80% illuminated could be Waxing Gibbous or Waning Gibbous).

What do you think? @trevorturk

**Comment by trevorturk** [comment]
I think that's all reasonable. If it comes up again we can review my existing logic (mostly from Dark Sky's advice) and consider adding something to the readme or wiki. For now I think it makes sense not to add more than we feel confident into the API.
